[install]
# Use exact versions for reproducible builds
exact = false

[install.scopes]
# Configure any scoped packages if needed

[test]
# Configure test runner
preload = ["./test/setup.ts"]

[run]
# Configure run scripts
bun = true

[install.cache]
# Enable caching for faster installs
dir = ".bun"

[install.registry]
# Use npm registry
url = "https://registry.npmjs.org/"

# TypeScript configuration
[typescript]
# Enable TypeScript support
compilerOptions = { "jsx": "react-jsx" } 